# Generated by Django 6.0.2 on 2026-02-17 23:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="資格名")),
                (
                    "target_hours",
                    models.IntegerField(
                        help_text="合格に必要な総学習時間",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="目標学習時間(時間)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studied_at", models.DateTimeField(verbose_name="学習日時")),
                (
                    "duration",
                    models.IntegerField(
                        help_text="1回の学習時間",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="学習時間(分)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="tracker.goal",
                    ),
                ),
            ],
        ),
    ]
